# https://circleci.com/docs/2.0/config-intro/
# https://circleci.com/docs/2.0/configuration-reference/
# https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
# https://circleci.com/docs/2.0/tutorials/#sample-apps-with-companion-guides
version: 2
jobs:
  Build-Task:
    docker:  # https://circleci.com/docs/2.0/docker-image-tags.json
      - image: circleci/python:2.7.16-jessie-browsers
    steps:
      - checkout
      - run:
          name: 安装依赖
          command: |
            pip install -U setuptools
            pip install --user -r requirements.txt -r test-requirements.txt
      - run: 
          name: 单元测试
          command: |
            ~/.local/bin/nosetests
      # - run:
      #     name: DEPLOY
      #     command: |
      #       pip install --user twine s3pypi
      #       python setup.py sdist bdist_wheel
      #       ~/.local/bin/twine upload --skip-existing -u meiqia -p "${PYPI_PASSWORD}" dist/*
      #       ~/.local/bin/s3pypi --region "${AWS_REGION}" --bucket "${AWS_S3_BUCKET}"

workflows:
  version: 2
  My-Workflow:
    jobs:
      #- Build-Task
      - Build-Task:
          filters:
            branches:
              only: master
